"""Add email and personal_number to Driver

Revision ID: bf70a30c3800
Revises: 3c0fd3532841
Create Date: 2024-02-21 09:54:20.673788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf70a30c3800'
down_revision = '3c0fd3532841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('personal_number', sa.String(), nullable=False, server_default=''))
    op.add_column('drivers', sa.Column('court_division', sa.String(), nullable=False, server_default=''))
    op.add_column('drivers', sa.Column('email', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'email')
    op.drop_column('drivers', 'court_division')
    op.drop_column('drivers', 'personal_number')
    # ### end Alembic commands ###
